# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s22N-jda6Ka4lTBkQhozj4j7Eq2NjT8y
"""

!pip install faker

import pandas as pd
import numpy as np
from faker import Faker

fake = Faker()
np.random.seed(42)

n = 200

diagnoses = ['Diabetes', 'Hypertension', 'Flu', 'Asthma', 'Migraine']

synthetic_data = {
    "Patient_ID": [fake.uuid4() for _ in range(n)],
    "Age": np.random.normal(45, 15, n).astype(int),
    "Gender": np.random.choice(['Male', 'Female'], n),
    "Diagnosis": np.random.choice(diagnoses, n),
    "Treatment_Cost": np.random.normal(5000, 1500, n).round(2),
    "Follow_Up": np.random.choice(['Yes', 'No'], n)
}

df = pd.DataFrame(synthetic_data)

df["Age"] = df["Age"].apply(lambda x: 18 if x < 18 else x)

df.to_csv("synthetic_healthcare_data.csv", index=False)

print("Dataset Generated Successfully")

from google.colab import files
files.download("synthetic_healthcare_data.csv")